verbose: true
printshellcmds: true
jobs: 200 # Maximum number of jobs to run in parallel

executor: slurm
default-resources:
  slurm_account: golling
  slurm_partition: public-cpu,public-bigmem,shared-cpu,shared-bigmem
  runtime: 300 # minutes
  mem_mb: 32000
  threads: 4
sdm: apptainer
apptainer-args: >- # multi-line string
  --nv
  --bind /srv,/home
