
hydra:

  # listmerge: append

  job:
    chdir: True

  run:
    dir: ${paths.save_path}

defaults:
  - _self_
  - paths: default.yaml
  - variables_from_root: default.yaml
  - variables_to_save: GN2.yaml
  - root: default.yaml

maxevents: 100
tree: CollectionTree;1
style: FTAG # event