


glob_to_data: /home/algren/work/data/ATLASOpenData/

data_path: ${paths.glob_to_data}/data2016/
save_path: ${paths.glob_to_data}/dump_data2016/

# data_path: ${paths.glob_to_data}/top_nominal/
# save_path: ${paths.glob_to_data}/dump_top_nominal/

output_name: 'data2016'